#!/usr/bin/env bash
# This script will display information about subdomains.

func_print ()
{
	dns=$(dig "$2.$1" | awk '/ANSWER SECTION:/ { getline;print $4 }')
	ip=$(dig "$2.$1" | awk '/ANSWER SECTION:/ { getline;print $5 }')
	echo "The subdomain $2 is a $dns record and points to $ip"
}

if [ "$#" -lt 2 ]
then
	func_print "$1" "www"
	func_print "$1" "lb-01"
	func_print "$1" "web-01"
	func_print "$1" "web-02"
else
	func_print "$1" "$2"
fi

exit 0
